#!/bin/sh

## First, find where automake is installed and get the version
AMPATH=`which automake|sed 's/\/bin\/automake//'`
AMVER=`automake --version|grep automake|awk '{print $4}'|awk -F. '{print $1"."$2}'`

## Copy files from the automake directory
ln -sf $AMPATH/share/automake-$AMVER/missing .
ln -sf $AMPATH/share/automake-$AMVER/mkinstalldirs .
ln -sf $AMPATH/share/automake-$AMVER/install-sh .
ln -sf $AMPATH/share/automake-$AMVER/depcomp .

## run aclocal
if [ -r /usr/share/aclocal/gnome-common.m4 ]; then
	aclocal
else
	aclocal -I /usr/share/aclocal/gnome2-macros
fi

## libtool and intltool
libtoolize --force
intltoolize --force

## generate documentation
docdir=docs/reference/html
if [ -x `which doxygen` ]; then
	doxygen Doxyfile
	echo '# This file was generated by autogen.sh DO NOT EDIT' > $docdir/Makefile.am
	echo "" >> $docdir/Makefile.am
	echo 'docsdir = $(datadir)/doc/gchemutils/reference/html' >> $docdir/Makefile.am
	echo "" >> $docdir/Makefile.am
	echo -n "docs_DATA =" >> $docdir/Makefile.am
	for i in $docdir/*.html $docdir/*.png $docdir/*.css; do
		echo " \\" >> $docdir/Makefile.am
		echo -n "	"`basename $i` >> $docdir/Makefile.am
	done
	echo "" >> $docdir/Makefile.am
	echo 'EXTRA_DIST = $(docs_DATA)' >> $docdir/Makefile.am
	echo "" >> $docdir/Makefile.am
else
	echo "doxygen not found, documentation has not been built."
	touch $docdir/Makefile.am
fi

## autoheader, automake, autoconf
autoheader
automake --gnu
autoconf

## Job ended
echo "run ./configure with the appropriate options, the make and enjoy"
