debian/tmp/usr/lib/*.la usr/lib
debian/tmp/usr/lib/*.so usr/lib
debian/tmp/usr/lib/pkgconfig/* usr/lib/pkgconfig
debian/tmp/usr/lib/bonobo/servers/* usr/lib/bonobo/servers

debian/tmp/usr/include/gcu/* usr/include/gcu
debian/tmp/usr/include/gcu/chem3d/* usr/include/gcu/chem3d
debian/tmp/usr/include/gcu/chemistry/* usr/include/gcu/chemistry
debian/tmp/usr/include/gcu/crystalviewer/* usr/include/gcu/crystalviewer
debian/tmp/usr/include/gcu/gtkperiodic/* usr/include/gcu/gtkperiodic
