.\"     Title: gchemtable
.\"    Author: Jean Br\('efort <jean.brefort@normalesup.org>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: $Date: 2007-10-16 01:11:42 $
.\"    Manual: gnome-chemistry-utils
.\"    Source: gcu 0.10
.\"
.TH "GCHEMTABLE" "1" "$Date: 2007\-10\-16 01:11:42 $" "gcu 0.10" "gnome-chemistry-utils"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
gchemtable \- periodic table of the elements
.SH "DESCRIPTION"
.PP
\fBgchemtable\fR
is a periodic table of the elements application\&.
.SH "OPTIONS"
.PP
No options are available\&.
.SH "AUTHORS"
.PP
\fBJean Br\('efort\fR <\&jean\&.brefort@normalesup\&.org\&>
.sp -1n
.IP "" 4
Program author\&.
.PP
\fBDaniel Leidert\fR <\&daniel\&.leidert@wgdd\&.de\&>
.sp -1n
.IP "" 4
Manpage author\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2007 Jean Br\('efort
.br
Copyright \(co 2004-2007 Daniel Leidert
.br
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation\&.
.sp
