.\"     Title: gchemcalc
.\"    Author: Daniel Leidert <daniel.leidert@wgdd.de>
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: $Date: 2006-07-14 22:27:55 $
.\"    Manual: gnome\-chemistry\-utils
.\"    Source: gcu 0.6.2
.\"
.TH "GCHEMCALC" "1" "$Date: 2006-07-14 22:27:55 $" "gcu 0.6.2" "gnome\-chemistry\-utils"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
gchemcalc \- simple calculator for chemists
.SH "SYNOPSIS"
.HP 10
\fBgchemcalc\fR [\fBOPTION(S)\fR...] [\fIFORMULA\fR]
.SH "DESCRIPTION"
.PP

\fBgchemcalc\fR
is a simple calculator for chemists.
.SH "OPTIONS"
.PP
The following options are accepted:
.PP
\fB\-?\fR, \fB\-\-help\fR
.RS 3n
Show help options.
.RE
.TP 3n
\fB\-\-help\-all\fR
Show all help options.
.TP 3n
\fB\-\-help\-gtk\fR
Show only GTK+ options (not documented here).
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 3n
Print gchemcalc version information.
.RE
.SH "AUTHOR"
.PP
\fBDaniel\fR \fBLeidert\fR <daniel.leidert@wgdd.de>
.sp -1n
.IP "" 3n
Author.
