'\" t
.\"     Title: gchemtable
.\"    Author: Jean Br\('efort <jean.brefort@normalesup.org>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: $Date: 2008-09-01 21:48:58 +0200 (lun. 01 sept. 2008) $
.\"    Manual: gnome-chemistry-utils
.\"    Source: gcu 0.12
.\"  Language: English
.\"
.TH "GCHEMTABLE" "1" "$Date: 2008\-09\-01 21:48:58 +0200 (lun\&. 01 sept\&. 2008) $" "gcu 0.12" "gnome-chemistry-utils"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gchemtable \- periodic table of the elements
.SH "DESCRIPTION"
.PP
\fBgchemtable\fR
is a periodic table of the elements application\&.
.SH "OPTIONS"
.PP
No options are available\&.
.SH "AUTHORS"
.PP
\fBJean Br\('efort\fR <\&jean\&.brefort@normalesup\&.org\&>
.RS 4
Program author\&.
.RE
.PP
\fBDaniel Leidert\fR <\&daniel\&.leidert@wgdd\&.de\&>
.RS 4
Manpage author\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2002-2007 Jean Br\('efort
.br
Copyright \(co 2004-2007 Daniel Leidert
.br
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation\&.
.sp
