'\" t
.\"     Title: gchempaint
.\"    Author: Jean Br\('efort <jean.brefort@normalesup.org>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: $Date: 2010-04-26 11:32:26 +0200 (lun. 26 avril 2010) $
.\"    Manual: gnome-chemistry-utils
.\"    Source: gcu 0.12
.\"  Language: English
.\"
.TH "GCHEMPAINT" "1" "$Date: 2010\-04\-26 11:32:26 +0200 (lun\&. 26 avril 2010) $" "gcu 0.12" "gnome-chemistry-utils"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gchempaint \- 2D chemical structures editor for the GNOME2 desktop
.SH "SYNOPSIS"
.HP \w'\fBgchempaint\fR\ 'u
\fBgchempaint\fR [\fBOPTIONS\fR...] [\fIFILE\fR...]
.SH "DESCRIPTION"
.PP
\fBgchempaint\fR
is a 2D chemical structures editor for the GNOME2 desktop\&. It is a multi document application\&. You can read different file types with
\fBgchempaint\fR\&. E\&.g\&. chemical/x\-cml, chemical/x\-mdl\-molfile, chemical/x\-mdl\-sdfile or chemical/x\-pdb\&. But be aware, that you will maybe loose 3D\-data from these file\-formats\&.
.SH "OPTIONS"
.PP
Currently the following options are supported:
.PP
\fB\-e\fR, \fB\-\-edit\-residue\fR
.RS 4
Open residues dialog\&.
.RE
.PP
\fB\-F\fR, \fB\-\-full\-screen\fR
.RS 4
Open new windows full screen\&.
.RE
.PP
\fB\-M\fR, \fB\-\-maximize\fR
.RS 4
Open new window maximized\&.
.RE
.PP
\fB\-?\fR, \fB\-\-help\fR
.RS 4
Show application help options\&.
.RE
.PP
\fB\-\-help\-all\fR, \fB\-\-help\-*\fR
.RS 4
Print all or just a group of help options\&. These options are not documented here\&. Instead see
\fBgtk-options\fR(7)
and
\fBgnome-options\fR(7)\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Print gchempaint version information\&.
.RE
.SH "SEE ALSO"
.PP
\fBgnome-options\fR(7),
\fBgtk-options\fR(7)
.SH "AUTHORS"
.PP
\fBJean Br\('efort\fR <\&jean\&.brefort@normalesup\&.org\&>
.RS 4
Program author\&.
.RE
.PP
\fBDaniel Leidert\fR <\&daniel\&.leidert@wgdd\&.de\&>
.RS 4
Manpage author\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2002-2007 Jean Br\('efort
.br
Copyright \(co 2004-2007 Daniel Leidert
.br
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation\&.
.sp
