.\"     Title: gchem3d
.\"    Author: Jean Br\('efort <jean.brefort@normalesup.org>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: $Date: 2008-09-01 21:46:41 +0200 (lun 01 sep 2008) $
.\"    Manual: gnome-chemistry-utils
.\"    Source: gcu 0.10
.\"
.TH "GCHEM3D" "1" "$Date: 2008\-09\-01 21:46:41 +0200 (lun 01 sep 2008) $" "gcu 0.10" "gnome-chemistry-utils"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
gchem3d \- a small chemical viewer application
.SH "SYNOPSIS"
.HP 8
\fBgchem3d\fR [\fBOPTION(S)\fR...] [\fIFILE\fR...]
.SH "DESCRIPTION"
.PP
\fBgchem3d\fR
is a small chemical viewer application, which can show several chemical file formats\&.
.SH "OPTIONS"
.PP
The following options are accepted:
.PP
\fB\-b \fR\fB\fICOLOR\fR\fR, \fB\-\-bgcolor=\fR\fB\fICOLOR\fR\fR
.RS 4
Use the given color as background color\&.
\fICOLOR\fR
can be one of
"\fIblack\fR" (default), "\fIwhite\fR", "\fI#rrggbb\fR" (don\'t forget to escape the \(lq#\(rq character in the shell)\&.
.RE
.PP
\fB\-d \fR\fB\fIMODEL\fR\fR, \fB\-\-display3d=\fR\fB\fIMODEL\fR\fR
.RS 4
Choose how molecules are displayed\&.
\fIMODEL\fR
can be one of
"\fIBallnStick\fR" (default), "\fISpaceFill\fR"\&.
.RE
.PP
\fB\-?\fR, \fB\-\-help\fR
.RS 4
Show application help options\&.
.RE
.PP
\fB\-\-help\-all\fR, \fB\-\-help\-*\fR
.RS 4
Print all or just a group of help options\&. These options are not documented here\&. Instead see
\fBgtk-options\fR(7)
and
\fBgnome-options\fR(7)\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Print gchem3d version information\&.
.RE
.SH "SEE ALSO"
.PP
\fBgnome-options\fR(7),
\fBgtk-options\fR(7)
.SH "AUTHORS"
.PP
\fBJean Br\('efort\fR <\&jean\&.brefort@normalesup\&.org\&>
.sp -1n
.IP "" 4
Program author\&.
.PP
\fBDaniel Leidert\fR <\&daniel\&.leidert@wgdd\&.de\&>
.sp -1n
.IP "" 4
Manpage author\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2007 Jean Br\('efort
.br
Copyright \(co 2004-2007 Daniel Leidert
.br
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation\&.
.sp
