.\"     Title: libgcu
.\"    Author: Jean Br\('efort <jean.brefort@normalesup.org>
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: $Date: 2006-08-15 01:05:51 $
.\"    Manual: gnome\-chemistry\-utils
.\"    Source: gcu 0.6.2
.\"
.TH "LIBGCU" "3" "$Date: 2006-08-15 01:05:51 $" "gcu 0.6.2" "gnome\-chemistry\-utils"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
libgcu \- Gtk widgets and C++ classes related to chemistry
.SH "SYNOPSIS"
.sp
.RS 3n
.nf
\fB#include gcu/chemistry.h\fR
.fi
.RE
.SH "DESCRIPTION"
.PP
The
libgcu
library provides various Gtk widgets and C++ classes related to chemistry.
.SH "FILES"
.PP
.TP 3n
\fI${libdir}/libcgu.a\fR
static library
.TP 3n
\fI${libdir}/libcgu.so\fR
shared library
.SH "SEE ALSO"
.PP
The complete reference with examples is available online at
\fI\%http://www.nongnu.org/gchemutils/reference/\fR
or (depending on your installation) also locally at
\fI${datadir}/doc/gchemutils/reference\fR.
.SH "AUTHORS"
.PP
\fBJean\fR \fBBr\('efort\fR <jean.brefort@normalesup.org>
.sp -1n
.IP "" 3n
Program/Library author.
.PP
\fBDaniel\fR \fBLeidert\fR <daniel.leidert@wgdd.de>
.sp -1n
.IP "" 3n
Manpage author.
