.\"     Title: libgcu-unstable
.\"    Author: Jean Br\('efort <jean.brefort@normalesup.org>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: $Date: 2007-10-16 01:11:43 $
.\"    Manual: gnome-chemistry-utils
.\"    Source: gcu 0.9.2
.\"
.TH "LIBGCU\-UNSTABLE" "3" "$Date: 2007-10-16 01:11:43 $" "gcu 0.9.2" "gnome-chemistry-utils"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
libgcu-unstable - Gtk widgets and C++ classes related to chemistry
.SH "SYNOPSIS"
.sp
.RS 4
.nf
\fB#include gcu/chemistry\.h\fR
.fi
.RE
.SH "DESCRIPTION"
.PP
The
libgcu\-unstable
library provides various Gtk widgets and C++ classes related to chemistry\.
.SH "FILES"
.PP
.PP
\fI${libdir}/libcgu\.a\fR
.RS 4
static library
.RE
.PP
\fI${libdir}/libcgu\.so\fR
.RS 4
shared library
.RE
.SH "SEE ALSO"
.PP
The complete reference with examples is available online at
\fI\%http://www.nongnu.org/gchemutils/reference/\fR
or (depending on your installation) also locally at
\fI${datadir}/doc/gchemutils/reference\fR\.
.SH "AUTHORS"
.PP
\fBJean Br\('efort\fR <\&jean\.brefort@normalesup\.org\&>
.sp -1n
.IP "" 4
Program/Library author\.
.PP
\fBDaniel Leidert\fR <\&daniel\.leidert@wgdd\.de\&>
.sp -1n
.IP "" 4
Manpage author\.
.SH "COPYRIGHT"
Copyright \(co 2002-2007 Jean Br\('efort
.br
Copyright \(co 2004-2007 Daniel Leidert
.br
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation\.
.sp
