.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "LIBGCU" "3" "$Date: 2006-05-06 12:46:25 $" "gnome\-chemistry\-utils 0.6.1" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
libgcu \- Gtk widgets and C++ classes related to chemistry
.SH "SYNOPSIS"
.sp
.nf
\fB#include gcu/chemistry.h\fR
.fi
.SH "DESCRIPTION"
.PP
The
libgcu
library provides various Gtk widgets and C++ classes related to chemistry.
.SH "FILES"
.PP
.TP
\fI${libdir}/libcgu.a\fR
static library
.TP
\fI${libdir}/libcgu.so\fR
shared library
.SH "SEE ALSO"
.PP
The complete reference with examples is available online at
\fI\%http://www.nongnu.org/gchemutils/reference/\fR
or (depending on your distribution) also locally at
\fI${datadir}/doc/gchemutils/reference\fR.
.SH "AUTHOR"
Daniel Leidert <daniel.leidert@wgdd.de>. 
