.\"     Title: libgcu
.\"    Author: Jean Br\('efort <jean.brefort@normalesup.org>
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: $Date: 2006-09-13 01:41:42 $
.\"    Manual: gnome\-chemistry\-utils
.\"    Source: gcu 0.6.3
.\"
.TH "LIBGCU" "3" "$Date: 2006-09-13 01:41:42 $" "gcu 0.6.3" "gnome\-chemistry\-utils"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
libgcu \- Gtk widgets and C++ classes related to chemistry
.SH "SYNOPSIS"
.sp
.RS 3n
.nf
\fB#include gcu/chemistry.h\fR
.fi
.RE
.SH "DESCRIPTION"
.PP
The
libgcu
library provides various Gtk widgets and C++ classes related to chemistry.
.SH "FILES"
.PP
.PP
\fI${libdir}/libcgu.a\fR
.RS 3n
static library
.RE
.PP
\fI${libdir}/libcgu.so\fR
.RS 3n
shared library
.RE
.SH "SEE ALSO"
.PP
The complete reference with examples is available online at
\fI\%http://www.nongnu.org/gchemutils/reference/\fR
or (depending on your installation) also locally at
\fI${datadir}/doc/gchemutils/reference\fR.
.PP
On Debian systems, the package libgcu\-doc provides the documentation locally under
\fI/usr/share/doc/libgcu\-doc/reference\fR.
.SH "AUTHORS"
.PP
\fBJean\fR \fBBr\('efort\fR <\&jean.brefort@normalesup.org\&>
.sp -1n
.IP "" 3n
Program/Library author.
.PP
\fBDaniel\fR \fBLeidert\fR <\&daniel.leidert@wgdd.de\&>
.sp -1n
.IP "" 3n
Manpage author.

